import {
  IsIn,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
  ValidateIf,
} from 'class-validator';
import {
  FACTION_SYMBOL_TYPES,
  FACTION_TYPES,
  FactionSymbolType,
} from '../faction.constants';

/** Payload for creating a faction (JSON — the symbol is generated by AI). */
export class CreateFactionDto {
  @IsString()
  @IsNotEmpty()
  @MinLength(3)
  @MaxLength(120)
  name!: string;

  @IsIn(FACTION_TYPES as unknown as string[])
  type!: string;

  @ValidateIf((o) => o.type === 'custom')
  @IsString()
  @IsNotEmpty()
  @MaxLength(60)
  customType?: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  description?: string;

  @IsOptional()
  @IsString()
  @MaxLength(10000)
  history?: string;

  @IsOptional()
  @IsString()
  @MaxLength(10000)
  identity?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  memberTraits?: string;

  @IsOptional()
  @IsString()
  @MaxLength(500)
  values?: string;

  @IsOptional()
  @IsString()
  @MaxLength(200)
  motto?: string;

  @IsOptional()
  @IsString()
  @MaxLength(200)
  colors?: string;

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  recurringElements?: string;

  @IsIn(FACTION_SYMBOL_TYPES as unknown as string[])
  symbolType!: FactionSymbolType;

  @IsOptional()
  @IsString()
  @MaxLength(2000)
  symbolPrompt?: string;
}
